title:            Principal
description:      Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //emmanuelmaqueda.github.io
#http://localhost:5000
#https://jponttuset.github.io
disqus_shortname: emmanuelmaqueda
# Owner/author information
owner:
  name:           David Emmanuel Maqueda Bojorquez
  avatar:         foto.png
  bio:            " 'Demasiado juego para ser una ciencia y demasiada ciencia para ser un juego.' \n Leibniz "
  email:          dmaqueda71@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  t email:          dmaqueda71@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  facebook: demmanuel.maqueda
  instagram : e_maqueda
  twitter: emmanuelmaqueda
  linkedin: emmanuel-maqueda
  
  google_scholar: 2kcO-_EAAAAJ&hl
  #google_plus: 113718226018314522413
  github: emmanuelmaqueda
# Analytics and webmaster tools stuff goes here

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Curriculum
    url: /cv/
  - title: Ponencias y publicaciones 
    url: /publications/
  - title: Proyectos
    url: /code/
  - title: Blog y recursos
    url: /blog/
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Mexico_City
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

syntax_highlighter_opts:
  line_numbers:
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
